version: "3"
services:    
    web:
        image: "918261458107.dkr.ecr.eu-west-3.amazonaws.com/nro/interview-api:latest"
        logging:
            driver: awslogs
            options:
              awslogs-region: eu-west-3
              awslogs-group: /interview/app-logs
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 250M
        ports:
            - "8090:8080"
        environment:
            "interview.template": "file:///configuration/epreuve.html"
            "interview.url": "https://qcm.cloud-gfi-nord.fr/exam/@sessionId@/uuid/@uuid@"
            "quarkus.datasource.password": "%%ds_password%%"
            "quarkus.datasource.jdbc.url": "%%ds_url%%"
            "quarkus.datasource.username": "%%ds_username%%"
            "QUARKUS_LOG_CONSOLE_LEVEL": "%%log_console_level%%"
            "QUARKUS_LOG_LEVEL": "%%log_level%%"
            "quarkus.mailer.password": "%%mail_password%%"
            "QUARKUS_MAILER_USERNAME": "epsi.qcmonline"
            "DB_NAME": "%%db_name%%"
            "QUARKUS_HTTP_CORS": "false"
            "mp.jwt.verify.publickey.location": "file:///configuration/public-key.pem"
            "mp.jwt.verify.issuer": "https://quarkus.io/using-jwt-rbac"
            "quarkus.smallrye-jwt.auth-mechanism": "MP-JWT"
            "quarkus.smallrye-jwt.enabled": "true"
            "quarkus.datasource.db-kind": "mariadb"
            "quarkus.datasource.jdbc.driver": "org.mariadb.jdbc.Driver"
            "quarkus.hibernate-orm.dialect": "org.hibernate.dialect.MySQL57Dialect"
