version: "3.0"
services:    
    web:
        image: "918261458107.dkr.ecr.eu-west-3.amazonaws.com/nro/interview-api:latest"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 250M
        ports:
            - "8090:8080"
        environment:
            "interview.template": "file:///configuration/epreuve.html"
            "INTERVIEW.TEMPLATE": "file:///configuration/epreuve.html"
            "interview.url": "https://qcm.cloud-gfi-nord.fr/exam/@sessionId@/uuid/@uuid@"
            "MP_JWT_VERIFY_PUBLICKEY_LOCATION": "file:///configuration/public-key.pem"
            "QUARKUS_DATASOURCE_PASSWORD": "password"
            "QUARKUS_DATASOURCE_URL": "jdbc:mysql://sss.eu-west-3.rds.amazonaws.com:3306/interview-dev"
            "QUARKUS_DATASOURCE_USERNAME": "username"
            "QUARKUS_LOG_CONSOLE_LEVEL": "DEBUG"
            "QUARKUS_LOG_LEVEL": "DEBUG"
            "QUARKUS_MAILER_PASSWORD": "password"
            "QUARKUS_MAILER_USERNAME": "epsi.qcmonline"

