# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: marocchino/setup-ecs-cli@v1
      with:
        version: "v1.18.0"
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-  
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: upload image to ECR
      uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.aws_access_key_id }}
        secret_access_key: ${{ secrets.aws_secret_access_key }}
        account_id: ${{ secrets.account_id }}
        repo: nro/interview-api
        region: eu-west-3
        dockerfile: ./src/main/docker/Dockerfile.jvm
        path: .
        
    - name: Deploy ecs
      run: "ecs-cli compose start --file ./src/main/docker/docker-compose.jvm --project-name interview-ui --cluster-config my-project-prism-api"
        
    
